-- MIMIC-III v1.4 Data Load (from .csv.gz)
-- Before running, set MIMIC3_DIR in your shell to the directory
-- containing the *.csv.gz files (e.g., /path/to/mimic-iii), then invoke:
--   psql -v iii_dir=$MIMIC3_DIR -f load_mimic3.sql
-- (or replace :iii_dir with the literal path).
SET search_path TO mimiciii;

\cd :iii_dir

\copy ADMISSIONS FROM PROGRAM 'gzip -dc ADMISSIONS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy CALLOUT FROM PROGRAM 'gzip -dc CALLOUT.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy CAREGIVERS FROM PROGRAM 'gzip -dc CAREGIVERS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy CPTEVENTS FROM PROGRAM 'gzip -dc CPTEVENTS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy D_CPT FROM PROGRAM 'gzip -dc D_CPT.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy D_ICD_DIAGNOSES FROM PROGRAM 'gzip -dc D_ICD_DIAGNOSES.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy D_ICD_PROCEDURES FROM PROGRAM 'gzip -dc D_ICD_PROCEDURES.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy D_ITEMS FROM PROGRAM 'gzip -dc D_ITEMS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy D_LABITEMS FROM PROGRAM 'gzip -dc D_LABITEMS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy DATETIMEEVENTS FROM PROGRAM 'gzip -dc DATETIMEEVENTS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy DIAGNOSES_ICD FROM PROGRAM 'gzip -dc DIAGNOSES_ICD.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy DRGCODES FROM PROGRAM 'gzip -dc DRGCODES.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy ICUSTAYS FROM PROGRAM 'gzip -dc ICUSTAYS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy INPUTEVENTS_CV FROM PROGRAM 'gzip -dc INPUTEVENTS_CV.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy INPUTEVENTS_MV FROM PROGRAM 'gzip -dc INPUTEVENTS_MV.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy LABEVENTS FROM PROGRAM 'gzip -dc LABEVENTS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy MICROBIOLOGYEVENTS FROM PROGRAM 'gzip -dc MICROBIOLOGYEVENTS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy NOTEEVENTS FROM PROGRAM 'gzip -dc NOTEEVENTS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy OUTPUTEVENTS FROM PROGRAM 'gzip -dc OUTPUTEVENTS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy PATIENTS FROM PROGRAM 'gzip -dc PATIENTS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy PRESCRIPTIONS FROM PROGRAM 'gzip -dc PRESCRIPTIONS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy PROCEDUREEVENTS_MV FROM PROGRAM 'gzip -dc PROCEDUREEVENTS_MV.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy PROCEDURES_ICD FROM PROGRAM 'gzip -dc PROCEDURES_ICD.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy SERVICES FROM PROGRAM 'gzip -dc SERVICES.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy TRANSFERS FROM PROGRAM 'gzip -dc TRANSFERS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
\copy CHARTEVENTS FROM PROGRAM 'gzip -dc CHARTEVENTS.csv.gz' DELIMITER ',' CSV HEADER NULL ''
